### ISSUE TITLE
[Discussion] Get 0.12 out the Door

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/ChocolateyGUI#212]
Let's wrap up 0.12 (WPF Refresh).

What do we have left to do?
* [x] Make sure no bugs. - assigned to Gary and Richard
* [x] Produce roadmap or goals for 0.13 and Choco integration - assigned to Richard
* [x] Update Release Notes for 0.12 - assigned to Gary
* [x] Tag repo - assigned to Gary
* [x] Grab some screenshots of the application, and add to source - these can then be used for blog posts, documentation, etc. - assigned to Gary

**Comment by gep13** [comment]
In terms of what is left, this is it:

![image](https://cloud.githubusercontent.com/assets/1271146/6307704/f25daf80-b935-11e4-8bc7-34796ab0f252.png)

https://github.com/chocolatey/ChocolateyGUI/milestones/0.12#boards?milestone=2

I have a solution for #81 so I will get that added in over the weekend.

Packaging and deployment are handled by the build script, so as soon as we merge into master branch, and tag the repo, it should all happen automagically.

I agree that we should do a round of testing before pushing the button, just make sure all core features are working.  I have fixed up a few things that I noticed weren't quite right, but basically it seems sound to me.

I like the idea of a roadmap, I think that makes a lot of sense.

I have started that with creating milestones, and assigning issues to them:

https://github.com/chocolatey/ChocolateyGUI/milestones

But I like the idea of an overall roadmap for things that we are thinking about, and what is in the pipeline.

Liking the additions of the labels that you have made!

The planning/doing/etc ones aren't really required any more, as I have switched to using ZenHub, rather than Huboard.  Not sure if you are still using Huboard, if you are, can I suggest that you switch so we are both using the same?  I have found ZenHub to be much better, as you don't have to context switch to another tab, it is all in GitHub.

**Comment by RichiCoder1** [comment]
Discussion was continued in the [repo channel](gitter.im/chocolatey/ChocolateyGUI). All of this was discussed. Leaving open for community questions.

**Comment by gep13** [comment]
@RichiCoder1 I have updated the list of steps that need to be taken care of prior to shipping (this is the last outstanding issue in the 0.12 milestone so we can use it for tracking the remaining items).

Feel free to add in anything else that you think is necessary.

Can you take a look at the latest release on the MyGet Feed.  I am going to do some testing with it tomorrow, and assuming that everything else is completed, I am going to ship it :-)

**Comment by RichiCoder1** [comment]
I'll look at it as soon as I get in tomorrow (which will probably be late lunch for you)

**Comment by gep13** [comment]
> @RichiCoder1 said...
I'll look at it as soon as I get in tomorrow (which will probably be late lunch for you)

Not a problem at all, thanks!

**Comment by gep13** [comment]
@RichiCoder1 just wondering if you had a chance to look at this? Thanks!

**Comment by RichiCoder1** [comment]
:+1:

I would like to see abouts background color be changed to be more readable, but everything else looks solid.

**Comment by gep13** [comment]
Thanks for getting back to me!

What sort of colour were you thinking?  My design decisions would be questionable, at best :-)

I will try shipping this tonight :-)

**Comment by RichiCoder1** [comment]
The light Carmel color used on the package pages behind their markdowns descriptions should work. Sounds good!
