### ISSUE TITLE
Prepare 0.15 Release

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/ChocolateyGUI#349]
Let's get this out there!

ToDos:

- [x] Update Screenshots (#315)
- [x] Update Credits (#314) 
- [x] Bump version to 0.15.0 (@gep13)
- [x] Build release notes
- [x] Sign Release (@ferventcoder)

**Comment by gep13** [comment]
@RichiCoder1 in the above description, should it be 0.15.0?

**Comment by RichiCoder1** [comment]
@gep13 Just realized I messaed that up haha. It should indeed be 0.15. Fixed the milestone and title.

**Comment by pascalberger** [comment]
@RichiCoder1 Also the [Wiki](https://github.com/chocolatey/ChocolateyGUI/wiki/How-to-add-a-new-custom-source) seems to be outdated and should be updated for the new version.

**Comment by gep13** [comment]
I think that the wiki should be ripped out, in favour of some docs that are a bit closer to the code, so that we can at least attempt to update them with a new release of ChocolateyGUI.  I would want to use something like DocFx, or more likely Wyam, to generate a site, based on some markdown files stored directly in the repo.

@RichiCoder1 thoughts?

**Comment by RichiCoder1** [comment]
@gep13 I was literally coming here from the the email to say we should do exactly that :). DocFx + Github Pages = Yes.

**Comment by RichiCoder1** [comment]
We should think about securing the `gui.chocolatey.org` subdomain from @ferventcoder.

**Comment by gep13** [comment]
> @RichiCoder1 said...
We should think about securing the gui.chocolatey.org subdomain from @ferventcoder.

That is a fantastic idea! Rob?

**Comment by ferventcoder** [comment]
Interesting yes - that would be nice. We could also start integrating CLI / GUI docs together?

**Comment by ferventcoder** [comment]
But for now, maybe add a subdomain?

**Comment by RichiCoder1** [comment]
Yup. Just getting a subdomain going would be step #1

**Comment by magol** [comment]
How long does it take before this version is released?

**Comment by mwallner** [comment]
We're trying to get this out in the next couple of weeks :-)

**Comment by gep13** [comment]
@RichiCoder1 just updated the screenshots again, with the recent changes.

**Comment by ferventcoder** [comment]
First push had a couple of issues in new requirements for VERIFICATION/LICENSE, fixed that and have pushed again.
